select *
from NUTR_FOOD_REQS

select *
from NUTR_PATN_ADMT

--alter table NUTR_PATN_ADMT add ROOMNO char(5)
--alter table NUTR_PATN_ADMT add BEDNO char(10)

SELECT DISTINCT 
  A.WARDID, A.WARDNAME,
  A.ROOMNO, A.BEDNO, 
  P.TNAME+P.FNAME+' '+P.LNAME AS PATNAME,
  RQ.AMOUNTAM, RQ.AMOUNTPM 
FROM NUTR_FOOD_REQS RQ
LEFT JOIN NUTR_PATN_ADMT A ON A.AN = RQ.AN
LEFT JOIN NUTR_PATN P ON P.HN = A.HN

--ALTER TABLE NUTR_FOOD_REQS ADD PRINTED CHAR(1) NULL

SELECT *
FROM NUTR_FOOD_REQS

--UPDATE NUTR_FOOD_REQS SET PRINTED = 'N'