select *
from NUTR_FACT

--update NUTR_FACT set FGRP = 'diag',FGRC='03', FTYC='001'
--where FTYP = 'âÃ¤'

SELECT FDES
FROM NUTR_FACT
WHERE FGRP = 'diag'

select *
from NUTR_FOOD_REQS

SELECT *
FROM NUTR_PATN

SELECT *
FROM NUTR_PATN_ADMT

SELECT *
FROM NUTR_PATN_ADMT 

SELECT P.HN, A.AN, P.PID, 
       P.TNAME+P.FNAME+' '+P.LNAME AS PATNAME,
	   P.GENDER, P.BIRTH, A.WARDID, A.WARDNAME
FROM NUTR_PATN P 
LEFT JOIN NUTR_PATN_ADMT A ON A.HN = P.HN
WHERE A.AN = ''

--SELECT *
--INTO NUTR_PATN_TEMP
--FROM NUTR_PATN

------------------------DELETE DUPLICATE ROW--------------------------
--WITH CTE AS(
--   SELECT [HN], [PID], [TNAME], [FNAME], [LNAME], [GENDER], [BIRTH],
--       RN = ROW_NUMBER()OVER(PARTITION BY HN ORDER BY HN)
--   FROM NUTR_PATN

--)
--DELETE FROM CTE WHERE RN > 1

DELETE NUTR_FOOD_REQS WHERe REQID = '00004'