--INSERT INTO NUTR_FACT_GRPS
--VALUES('0001', 'PATIENT TYPE',0,'ประเภทผู้ป่วย')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0002', 'FOOD TYPE',0,'ประเภทอาหาร')
 
--INSERT INTO NUTR_FACT_GRPS
--VALUES('0021', 'FOOD LIQUID',1,'อาหารเหลว')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0022', 'DIET SOFT',1,'อาหารอ่อน')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0221', 'DIET SOFT NORMAL',2,'อาหารอ่อนปกติ')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0222', 'DIET SOFT SPECIAL',2,'อาหารอ่อนเฉพาะโรค')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('2221', 'DIET FOFT APPEARANCE',3,'ลักษณะอาหาร')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('2222', 'DIET FOFT TYPE',3,'ชนิดอาหาร')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0023', 'NORMAL FOOD',3,'อาหารธรรมดา')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0231', 'NORMAL FOOD',2,'อาหารธรรมดาปกติ')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0232', 'SPECILAL FOOD',2,'อาหารเฉพาะโรค')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0024', 'FEED',3,'อาหารสายยาง')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0241', 'FEED NORMAL',2,'ลาหารสายยางปกติ')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0242', 'FEED SPECIAL',2,'อาหารสายยางเฉพาะโรค')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('2421', 'FEED SPECIAL TYPE',2,'ชนิดอาหารสายยางเฉพาะโรค','P')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('2422', 'FEED SPECIAL CONCENTRATE',3,'ความเข้มข้นอาหารสายยางเฉพาะโรค','P')

--INSERT INTO NUTR_FACT_GRPS
--VALUES('0003', 'FEED RESTRICTION',2,'ข้อจำกัด','0')