select *
from NUTR_PATN

select *
from NUTR_PATN_ADMT

--SELECT 
--  P.HN, P.PID, P.TNAME, P.FNAME, P.LNAME, P.GENDER, P.BIRTH,
--  A.AN, A.WARDID, A.WARDNAME, A.ADMITDATE, A.DISCHDATE, A.ROOMNO, A.BEDNO 
--INTO NUTR_PADM
--FROM NUTR_PATN P 
--LEFT JOIN NUTR_PATN_ADMT A ON A.HN = P.HN

SELECT *
FROM NUTR_PADM