--select *
--from NUTR_FOOD_REQS

--select *
--from NUTR_PATN_ADMT



--SELECT DISTINCT 
--  A.WARDID, A.WARDNAME,
--  ISNULL(A.ROOMNO,'') AS ROOMNO, ISNULL(A.BEDNO,'') AS BEDNO, 
--  P.TNAME+P.FNAME+' '+P.LNAME AS PATNAME,
--  RQ.AMOUNTAM, RQ.AMOUNTPM 
--FROM NUTR_FOOD_REQS RQ
--LEFT JOIN NUTR_PATN_ADMT A ON A.AN = RQ.AN
--LEFT JOIN NUTR_PATN P ON P.HN = A.HN


--SELECT *
--FROM NUTR_FOOD_REQS

SELECT /*DISTINCT*/ P.WARDID, P.WARDNAME,
ISNULL(P.ROOMNO,'') AS ROOMNO,
ISNULL(P.BEDNO,'')  AS BEDNO,
P.HN,
P.TNAME+P.FNAME+' '+P.LNAME AS PATNAME,
RQ.AMOUNTAM, RQ.AMOUNTPM, RQ.SALTWT,
RQ.REQFR, RQ.REQTO,
GETDATE() AS PRNDATE,
RQ.FOODREQDESC
FROM NUTR_PADM P
JOIN NUTR_FOOD_REQS RQ ON RQ.HN = P.HN
                      AND RQ.AN = RQ.AN
--WHERE '2015-12-04' BETWEEN RQ.REQFR AND RQ.REQTO