--ALTER TABLE NUTR_FACT ALTER COLUMN CODE CHAR(8) NOT NULL
--ALTER TABLE NUTR_FACT ADD FGRC CHAR(2) NULL, FTYC CHAR(3) NULL
-----------------------------------------------------------------
--ALTER TABLE NUTR_PATN_ADMT ADD ROOMNO CHAR(5)
--ALTER TABLE NUTR_PATN_ADMT ADD BEDNO CHAR(10)
--ALTER TABLE NUTR_FOOD_REQS ADD PRINTED CHAR(1) NULL
--UPDATE NUTR_FOOD_REQS SET PRINTED = 'N'
--ALTER TABLE NUTR_FOOD_REQS ADD SALTWT FLOAT NULL
--ALTER TABLE NUTR_FACT ALTER COLUMN NOTE VARCHAR(250) NULL
--ALTER TABLE NUTR_FACT ADD PCOD VARCHAR(8) NULL
-----------------------------------------------------------------
--ALTER TABLE NUTR_FACT ALTER COLUMN FTYP VARCHAR(30) NULL
--ALTER TABLE NUTR_FOOD_REQS ADD FOODTYPC CHAR(8) NULL
-----------------------------------------------------------------
--ALTER TABLE NUTR_FOOD_REQS ADD FEED VARCHAR(8) NULL]
-----------------------------------------------------------------
--ALTER TABLE NUTR_PADM ADD RELGCODE CHAR(2) NULL, RELGDESC VARCHAR(30) NULL 
------------------------------------------------------------------
--ALTER TABLE NUTR_FOOD_REQS ALTER COLUMN REQID CHAR(5) NOT NULL
--ALTER TABLE NUTR_FOOD_REQS ALTER COLUMN HN CHAR(7) NOT NULL
--ALTER TABLE NUTR_FOOD_REQS ALTER COLUMN AN CHAR(7) NOT NULL
------------------------------------------------------------------
--ALTER TABLE NUTR_FOOD_REQS ADD REQDATE DATETIME NULL
------------------------------------------------------------------
--ALTER TABLE NUTR_FACT ADD LEV SMALLINT NULL

--CREATE TABLE NUTR_FACT_GRPS (FGRC CHAR(2) NOT NULL, FGRP VARCHAR(20) NOT NULL, FLEV INT NOT NULL)
--ALTER TABLE NUTR_FACT_GRPS ADD NOTE VARCHAR(100) NULL
--ALTER TABLE NUTR_FACT_GRPS ALTER COLUMN FGRC CHAR(4) NOT NULL
--ALTER TABLE NUTR_FACT_GRPS ALTER COLUMN FGRP VARCHAR(30)
--ALTER TABLE NUTR_FACT_GRPS ADD FPRP CHAR(1) NULL
--ALTER TABLE NUTR_FACT_GRPS ADD PCOD CHAR(4) NULL

-----------------------------------------------------------------
--ALTER TABLE NUTR_FACT ALTER COLUMN FGRC CHAR(4) NOT NULL

-----------------------------------------------------------------
--ALTER TABLE NUTR_FOOD_REQS ADD PATTYPE CHAR(8) NULL
--ALTER TABLE NUTR_FOOD_REQS ADD FOODPROP1 CHAR(8) NULL
--ALTER TABLE NUTR_FOOD_REQS ADD FOODPROP2 CHAR(8) NULL
--ALTER TABLE NUTR_FOOD_REQS ADD FOODRESTR CHAR(8) NULL
--ALTER TABLE NUTR_FOOD_REQS ADD FOODREQDESC VARCHAR(100) NULL

-----------------------------------------------------------------
--ALTER TABLE NUTR_FACT_GRPS ALTER COLUMN FPRP VARCHAR(2) NULL

--ALTER TABLE NUTR_FACT_REQS ADD FOODPROP3 CHAR(8) NULL

ALTER TABLE NUTR_FACT_GRPS ALTER COLUMN FGRP VARCHAR(50) NULL

ALTER TABLE NUTR_FOOD_REQS ADD FOODPROP3 CHAR(8) NULL
ALTER TABLE NUTR_FOOD_REQS ADD NOTE VARCHAR(50) NULL

CREATE TABLE NUTR_FOOD_REQD (REQID CHAR(5) NOT NULL,
                             REQCODE CHAR(8) NOT NULL,
							 REQDESC VARCHAR(50) NOT NULL)

ALTER TABLE NUTR_FOOD_REQS ALTER COLUMN FOODREQDESC VARCHAR(200) NULL