SELECT *
FROM NUTR_FOOD_REQS

SELECT *
FROM NUTR_FACT

--Column
SELECT CODE, FDES ,NOTE
FROM NUTR_FACT 
WHERE FGRC = '01'
AND FTYC = '001'

--Row
SELECT CODE, FDES, NOTE
FROM NUTR_FACT 
WHERE CODE = '00001001'

--Data
SELECT RQ.REQID, RQ.FOODTYPC, RQ.AMOUNTAM, RQ.AMOUNTPM, 
       PA.NOTE AS FORMULA_TPL,
       FA.NOTE AS FORMULA_VAL,
	   FA.CODE AS CODE,
	   FA.FDES AS DESCRP
FROM NUTR_FOOD_REQS RQ
LEFT JOIN NUTR_FACT FA ON FA.CODE = RQ.FOODTYPC
LEFT JOIN NUTR_FACT PA ON PA.CODE = FA.PCOD
WHERE ISNULL(RQ.FOODTYPC ,'') <> ''
AND FA.FGRC = '01'
AND FA.FTYC= '001'
ORDER BY RQ.FOODTYPC