 SELECT   
   P.WARDID, P.WARDNAME,  
   ISNULL(P.ROOMNO,'') AS ROOMNO,  
   ISNULL(P.BEDNO,'')  AS BEDNO,  
   P.HN,  
   P.TNAME+P.FNAME+' '+P.LNAME AS PATNAME,  
   P.RELGDESC,
   GETDATE() AS PRNDATE,  
   RQ.REQID, RQ.FOODREQDESC, RQ.REQDATE, RQ.DIAG, RQ.MEALORD,  
   RQ.COMDIS, RQ.MEALORD   
 FROM NUTR_PADM P   
 JOIN NUTR_FOOD_REQS RQ ON RQ.HN = P.HN   
                       AND RQ.AN = RQ.AN   
 JOIN   
 (SELECT DISTINCT REQID   
  FROM NUTR_FOOD_REQD   
  WHERE EXISTS (SELECT *   
                FROM NUTR_FACT_GRPS G   
                JOIN NUTR_FACT F ON F.FGRC = G.FGRC   
                WHERE SLIPPRN = 'Y'  )) B ON B.REQID = RQ.REQID   
 JOIN   
 (SELECT AN, MAX(REQDATE) AS REQDATE   
  FROM NUTR_FOOD_REQS   
  GROUP BY AN) C ON C.AN = RQ.AN   
                AND C.REQDATE = RQ.REQDATE   
 WHERE ISNULL(RQ.REQEND,'') <> 'Y'     
 ORDER BY WARDID, HN 

 SELECT *
 FROM NUTR_PADM