USE DEVNUT

--SELECT *
--FROM NUTR_FOOD_REQS

--SELECT *
--FROM NUTR_FACT
--WHERE CODE = '01001014'

--Column
--SELECT CODE, FDES ,NOTE
--FROM NUTR_FACT 
--WHERE FGRC = '01'
--AND FTYC = '001'

--Row Head
--SELECT CODE, FDES, NOTE
--FROM NUTR_FACT 
--WHERE CODE = '00001001'

--Data
--SELECT RQ.REQID, RQ.FOODTYPC, RQ.AMOUNTAM, RQ.AMOUNTPM, 
--       PA.NOTE AS FORMULA_TPL,
--       FA.NOTE AS FORMULA_VAL,
--	   FA.CODE AS CODE,
--	   FA.FDES AS DESCRP
--FROM NUTR_FOOD_REQS RQ
--LEFT JOIN NUTR_FACT FA ON FA.CODE = RQ.FOODTYPC
--LEFT JOIN NUTR_FACT PA ON PA.CODE = FA.PCOD
--WHERE ISNULL(RQ.FOODTYPC ,'') <> ''
--AND FA.FGRC = '01'
--AND FA.FTYC= '001'
--ORDER BY RQ.FOODTYPC

--SELECT CODE, FDES ,NOTE
--FROM NUTR_FACT 
--WHERE FGRC = '01'
--AND FTYC = '001'

--DECLARE @AllValues VARCHAR(4000)

--SELECT @AllValues = COALESCE(@AllValues + ',', '') + FDES
--FROM NUTR_FACT
--WHERE FGRC = '01'
--AND FTYC = '001'

--Data New

--SELECT F.CODE, 
--       ISNULL(C.TOTALAM,0) AS TOTALAM, 
--	   ISNULL(C.TOTALPM,0) AS TOTALPM, 
--	   ISNULL(C.CNT,0)     AS CNT
--FROM NUTR_FACT F
--LEFT JOIN (SELECT RQ.FOODTYPC, 
--                  SUM(RQ.AMOUNTAM) TOTALAM, 
--	              SUM(RQ.AMOUNTPM) TOTALPM, 
--	              COUNT(*) CNT
--           FROM NUTR_FOOD_REQS RQ
--           WHERE ISNULL(RQ.FOODTYPC ,'') <> ''
--           GROUP BY RQ.FOODTYPC) C ON C.FOODTYPC = F.CODE
--WHERE FGRC = '01'
--AND FTYC = '001'


--SELECT F.CODE,ISNULL(C.TOTALAM,0) AS TOTALAM,ISNULL(C.TOTALPM,0) AS TOTALPM,ISNULL(C.CNT,0)     AS CNT FROM NUTR_FACT F LEFT JOIN (SELECT RQ.FOODTYPC,SUM(RQ.AMOUNTAM) TOTALAM,SUM(RQ.AMOUNTPM) TOTALPM,COUNT(*) CNT FROM NUTR_FOOD_REQS RQ WHERE ISNULL(RQ.FOODTYPC ,') <> ''GROUP BY RQ.FOODTYPC) C ON C.FOODTYPC = F.CODE WHERE FGRC = '01'AND FTYC = '001'



--REPORT 1
--SELECT RQ.HN, RQ.MEALORD, RQ.FOODREQDESC,
--       PA.TNAME, PA.FNAME, PA.LNAME,
--	   PA.WARDID, PA.WARDNAME, PA.ROOMNO, PA.BEDNO, 
--	   CHARINDEX('>',RQ.FOODREQDESC,1)
    
--FROM NUTR_FOOD_REQS RQ
--LEFT JOIN NUTR_PADM PA ON PA.AN = RQ.AN
--WHERE ISNULL(RQ.REQEND,'') <> 'Y'
--AND ISNULL(RQ.FOODREQDESC,'') <> ''

--SELECT * , CONVERT(INT,REQCODE) 
--FROM NUTR_FOOD_REQD
--WHERE REQCODE <> 'freetext'

--SELECT *
--FROM
--(SELECT FGRC, FGRP, PCOD
--FROM NUTR_FACT_GRPS
--WHERE FLEV = 1) A

--SELECT *
--FROM
--(SELECT FGRC AS GC3, FGRP AS GP3, PCOD AS P3
--FROM NUTR_FACT_GRPS
--WHERE FLEV = 3) C
--LEFT JOIN (SELECT FGRC AS GC2, FGRP AS GP2, PCOD AS P2
--           FROM NUTR_FACT_GRPS
--           WHERE FLEV = 2) B ON B.GC2 = C.P3
--LEFT JOIN (SELECT FGRC AS GC1, FGRP AS GP1, PCOD AS P1
--           FROM NUTR_FACT_GRPS
--           WHERE FLEV = 1) A ON A.GC1 = B.P2

--SELECT *
--FROM NUTR_FACT F
--LEFT JOIN
--(SELECT *
--FROM
--(SELECT FGRC AS GC3, FGRP AS GP3, PCOD AS P3
--FROM NUTR_FACT_GRPS
--WHERE FLEV = 3) D
--LEFT JOIN (SELECT FGRC AS GC2, FGRP AS GP2, PCOD AS P2
--           FROM NUTR_FACT_GRPS
--           WHERE FLEV = 2) C ON C.GC2 = D.P3
--LEFT JOIN (SELECT FGRC AS GC1, FGRP AS GP1, PCOD AS P1
--           FROM NUTR_FACT_GRPS
--           WHERE FLEV = 1) B ON B.GC1 = C.P2
--LEFT JOIN (SELECT FGRC AS GC0, FGRP AS GP0, PCOD AS P0
--           FROM NUTR_FACT_GRPS
--           WHERE FLEV = 0) A ON A.GC0 = B.P1) G ON (G.GC0 = F.FGRC)OR(G.GC1 = F.FGRC)OR(G.GC2=F.FGRC)OR(G.GC3=F.FGRC) 
--WHERE ISNULL(P1,'') <> ''


--select *
--from NUTR_FACT

--select *
--from NUTR_FACT_GRPS

--select *
--from NUTR_FACT_GRPS
--where FLEV = 1

--select F.CODE, F.FDES, G.FGRC, G.FGRP, FLEV
--from NUTR_FACT F
--left join NUTR_FACT_GRPS G on G.FGRC = F.FGRC
--where G.FLEV =1 

--select F.CODE, F.FDES, G.FGRC, G.FGRP, FLEV
--from NUTR_FACT F
--left join NUTR_FACT_GRPS G on G.FGRC = F.FGRC
--where G.FLEV =2

--select F.CODE, F.FDES, G.FGRC, G.FGRP, FLEV
--from NUTR_FACT F
--left join NUTR_FACT_GRPS G on G.FGRC = F.FGRC
--where G.FLEV =3

--DECLARE @childID INT 
--SET @childID  = 1 --chield to search

--;WITH RCTE AS
--(
--    SELECT *, 1 AS Lvl FROM RelationHierarchy 
--    WHERE ChildID = @childID

--    UNION ALL

--    SELECT rh.*, Lvl+1 AS Lvl FROM dbo.RelationHierarchy rh
--    INNER JOIN RCTE rc ON rh.CHildId = rc.ParentId
--)
--SELECT TOP 1 id, Name
--FROM RCTE r
--inner JOIN dbo.Person p ON p.id = r.ParentId
--ORDER BY lvl DESC



--DECLARE @childID char(4) 
--SET @childID  = '2221'

--;WITH RCTE AS
--(
--    SELECT *, 1 AS Lvl FROM NUTR_FACT_GRPS 
--    WHERE FGRC = @childID

--    UNION ALL

--    SELECT rh.*, Lvl+1 AS Lvl FROM NUTR_FACT_GRPS  rh
--    INNER JOIN RCTE rc ON rh.FGRC = rc.FGRC
--)
--SELECT top 10 * FROM RCTE


--CREATE FUNCTION  dbo.GetFgrc(@fgrc char(4), @flevel int)
--RETURNS char(4)
--AS
--begin
--declare @ret char(4)

--;WITH RCTE AS
--(
--    SELECT  FGRC,FGRP,FLEV,PCOD FROM NUTR_FACT_GRPS 
--    WHERE FGRC = @fgrc
--    UNION ALL

--    SELECT rh.FGRC, rh.FGRP, rh.FLEV, rh.PCOD FROM NUTR_FACT_GRPS  rh
--    INNER JOIN RCTE rc ON rh.FGRC = rc.PCOD
--)
--SELECT  @ret = FGRC  FROM RCTE
--WHERE FLEV = @flevel

--Return @ret
--end 

--select  *, (select * from dbo.GetFgrc(F.FGRC,1)) 
--from NUTR_FACT F

--WITH RCTE AS
--(
--    SELECT  FGRC,FGRP,FLEV,PCOD FROM NUTR_FACT_GRPS 
--    UNION ALL

--    SELECT rh.FGRC, rh.FGRP, rh.FLEV, rh.PCOD FROM NUTR_FACT_GRPS  rh
--    INNER JOIN RCTE rc ON rh.FGRC = rc.PCOD
--)
--SELECT DISTINCT  * FROM RCTE

--LEFT JOIN NUTR_FACT F on F.FGRC = RCTE.FGRC
--WHERE FLEV = 1
 
--with name_tree as (
--   SELECT  FGRC,FGRP,FLEV,PCOD FROM NUTR_FACT_GRPS
--   WHERE FGRC = '2221'

--   union all
--   SELECT  C.FGRC, C.FGRP, C.FLEV, C.PCOD FROM NUTR_FACT_GRPS C
--     join name_tree p on p.PCOD = C.FGRC  
--) 
--select *
--from name_tree
--where FGRC <> '2221'
 
--WITH GRP_TREE AS (
--   SELECT  FGRC,FGRP,FLEV,PCOD FROM NUTR_FACT_GRPS
--   WHERE FGRC = '2221'

--   UNION ALL
--   SELECT  C.FGRC, C.FGRP, C.FLEV, C.PCOD FROM NUTR_FACT_GRPS C
--     JOIN GRP_TREE P ON P.PCOD = C.FGRC  
--) 
--SELECT *
--FROM GRP_TREE
--WHERE FGRC <> '2221'
--AND FLEV = 1


--CREATE FUNCTION ParGrpLev(@fgrc char(4), @lev int)
--RETURNS char(4)
--AS 
--BEGIN
--declare @ret char(4)
--;WITH GRP_TREE AS (
--   SELECT  FGRC,FGRP,FLEV,PCOD FROM NUTR_FACT_GRPS
--   WHERE FGRC = @fgrc

--   UNION ALL
--   SELECT  C.FGRC, C.FGRP, C.FLEV, C.PCOD FROM NUTR_FACT_GRPS C
--     JOIN GRP_TREE P ON P.PCOD = C.FGRC  
--) 
--SELECT @ret = FGRC
--FROM GRP_TREE
--WHERE FGRC <> @lev
--AND FLEV = 1
--return @ret
--END

--SELECT DISTINCT A.REQID,A.LEV1, G.FGRP --A.*, G.FGRP
--FROM
--(SELECT *,  
--       dbo.ParGrpLev(F.FGRC,1) AS LEV1,   
--	   dbo.ParGrpLev(F.FGRC,0) AS LEV0  
--FROM NUTR_FOOD_REQD R
--LEFT JOIN NUTR_FACT F ON F.CODE = R.REQCODE
--WHERE REQCODE <> 'freetext') A
--LEFT JOIN NUTR_FACT_GRPS G ON G.FGRC = A.LEV1
--WHERE A.REQID = '00008'
--AND A.LEV0 = '0002'


--REPORT 1
--SELECT RQ.REQID, RQ.HN, RQ.MEALORD, RQ.FOODREQDESC,
--       PA.TNAME, PA.FNAME, PA.LNAME,
--	   PA.WARDID, PA.WARDNAME, PA.ROOMNO, PA.BEDNO, 
--	   B.FGRC1, B.FGRP    
--FROM NUTR_FOOD_REQS RQ
--LEFT JOIN NUTR_PADM PA ON PA.AN = RQ.AN
--LEFT JOIN
--(SELECT DISTINCT A.REQID,A.FGRC1, G.FGRP 
--FROM
--(SELECT *,  
--       dbo.ParGrpLev(F.FGRC,1) AS FGRC1,   
--	   dbo.ParGrpLev(F.FGRC,0) AS FGRC0  
--FROM NUTR_FOOD_REQD R
--LEFT JOIN NUTR_FACT F ON F.CODE = R.REQCODE
--WHERE REQCODE <> 'freetext') A
--LEFT JOIN NUTR_FACT_GRPS G ON G.FGRC = A.FGRC1
--WHERE A.FGRC0= '0002') B ON B.REQID = RQ.REQID
--WHERE ISNULL(RQ.REQEND,'') = 'Y'
--AND ISNULL(RQ.FOODREQDESC,'') <> ''


SELECT ROW_NUMBER OVER 
       RQ.REQID, RQ.HN, RQ.MEALORD, RQ.FOODREQDESC,
       DATEDIFF(YYYY,PA.BIRTH,GETDATE()) AS AGE,
       RQ.REQDATE, RQ.HTS, RQ.WTS,
       PA.TNAME, PA.FNAME, PA.LNAME,
       PA.WARDID, PA.WARDNAME, PA.ROOMNO, PA.BEDNO,
       B.FGRC, B.FGRP,
	   D.[DES] AS DIAGDESC
FROM NUTR_FOOD_REQS RQ 
LEFT JOIN NUTR_PADM PA ON PA.AN = RQ.AN 
LEFT JOIN (SELECT DISTINCT A.REQID, A.FGRC1 AS FGRC, G.FGRP 
           FROM (SELECT *,
                        dbo.ParGrpLev(F.FGRC,1) AS FGRC1,
                        dbo.ParGrpLev(F.FGRC,0) AS FGRC0 
                 FROM NUTR_FOOD_REQD R 
                 LEFT JOIN NUTR_FACT F ON F.CODE = R.REQCODE 
                 WHERE REQCODE <> 'freetext') A 
           LEFT JOIN NUTR_FACT_GRPS G ON G.FGRC = A.FGRC1 
           WHERE A.FGRC0= '0002') B ON B.REQID = RQ.REQID 
LEFT JOIN NUTR_DIAG D ON D.CODE = RQ.DIAG
WHERE ISNULL(RQ.REQEND,'') = 'Y' 
AND ISNULL(RQ.FOODREQDESC,'') <> ''
AND RQ.REQDATE = '2016-02-26'

--CREATE VIEW DIAGLIST
--AS
--SELECT *, RTRIM(CODE)+':'+[DES] AS FULLDES
--INTO DIAGLIST
--FROM DEVHC.dbo.ICD101 (NOLOCK)
--WHERE CODE BETWEEN 'E110' AND 'E119'
--OR CODE = 'I10'
--OR CODE BETWEEN 'E780' AND 'E789'
--OR CODE = 'N179'
--OR CODE = 'N19'
--OR CODE BETWEEN 'N181' AND 'N185'
--OR CODE BETWEEN 'M100' AND 'M109'
--OR CODE BETWEEN 'I20.0' AND 'I25.9'
--OR CODE LIKE 'C%'
--OR CODE BETWEEN 'E660' AND 'E669'
--OR CODE BETWEEN 'I630' AND 'I639'
--OR CODE = 'I64'

--select *
--from DIAGLIST

--SELECT
--    col.name, col.collation_name
--FROM 
--    sys.columns col
--WHERE
--    object_id = OBJECT_ID('NUTR_FOOD_REQS')

--ALTER TABLE dbo.NUTR_FOOD_REQS ALTER COLUMN DIAG  
--            varchar(50)COLLATE THAI_BIN NULL; 

--ALTER TABLE NUTR_DIAG ALTER COLUMN CODE CHAR(7) NOT NULL

--ALTER TABLE NUTR_DIAG   
--ADD CONSTRAINT PK_NUTR_DIAG PRIMARY KEY CLUSTERED (CODE); 

--ALTER TABLE NUTR_FOOD_REQS ALTER COLUMN DIAG CHAR(7) COLLATE THAI_BIN NOT NULL


--select *
--from NUTR_DIAG
--where CODE = null