USE [DEVNUT]
GO

----NUTR_CTRL
--/****** Object:  Index [PK_NUTR_CTRL]    Script Date: 22/10/2559 9:32:18 ******/
--ALTER TABLE [dbo].[NUTR_CTRL] ADD  CONSTRAINT [PK_NUTR_CTRL] PRIMARY KEY CLUSTERED 
--(
--	[ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

----NUTR_FACT
--/****** Object:  Index [PK_NUTR_FACT]    Script Date: 22/10/2559 9:38:23 ******/
--ALTER TABLE [dbo].[NUTR_FACT] ADD  CONSTRAINT [PK_NUTR_FACT] PRIMARY KEY NONCLUSTERED 
--(
--	[CODE] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--ALTER TABLE [dbo].[NUTR_FACT]  WITH CHECK ADD  CONSTRAINT [FK_NUTR_FACT_NUTR_FACT_GRPS] FOREIGN KEY([FGRC])
--REFERENCES [dbo].[NUTR_FACT_GRPS] ([FGRC])
--GO

--ALTER TABLE [dbo].[NUTR_FACT] CHECK CONSTRAINT [FK_NUTR_FACT_NUTR_FACT_GRPS]
--GO

/****** Object:  Index [IDX0_NUTR_FACT]    Script Date: 22/10/2559 9:39:26 ******/
--CREATE UNIQUE CLUSTERED INDEX [IDX0_NUTR_FACT] ON [dbo].[NUTR_FACT]
--(
--	[CODE] ASC,
--	[FGRC] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

/****** Object:  Index [PK_NUTR_FOOD_REQD]    Script Date: 22/10/2559 9:41:58 ******/
--ALTER TABLE [dbo].[NUTR_FOOD_REQD] ADD  CONSTRAINT [PK_NUTR_FOOD_REQD] PRIMARY KEY NONCLUSTERED 
--(
--	[REQID] ASC,
--	[REQCODE] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQD]  WITH CHECK ADD  CONSTRAINT [FK_NUTR_FOOD_REQD_NUTR_FOOD_REQS] FOREIGN KEY([REQID])
--REFERENCES [dbo].[NUTR_FOOD_REQS] ([REQID])
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQD] CHECK CONSTRAINT [FK_NUTR_FOOD_REQD_NUTR_FOOD_REQS]
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQD]  WITH CHECK ADD  CONSTRAINT [FK_NUTR_FOOD_REQD_NUTR_FACT] FOREIGN KEY([REQCODE])
--REFERENCES [dbo].[NUTR_FACT] ([CODE])
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQD] CHECK CONSTRAINT [FK_NUTR_FOOD_REQD_NUTR_FACT]
--GO

--NUTR_FACT_GRPS
--/****** Object:  Index [IDX0_NUTR_FACT_GRPS]    Script Date: 22/10/2559 10:00:47 ******/
--CREATE UNIQUE CLUSTERED INDEX [IDX0_NUTR_FACT_GRPS] ON [dbo].[NUTR_FACT_GRPS]
--(
--	[FGRC] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--/****** Object:  Index [PK_NUTR_FACT_GRPS]    Script Date: 22/10/2559 10:02:03 ******/
--ALTER TABLE [dbo].[NUTR_FACT_GRPS] ADD  CONSTRAINT [PK_NUTR_FACT_GRPS] PRIMARY KEY NONCLUSTERED 
--(
--	[FGRC] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO


--NUTR_FOOD_REQD
/****** Object:  Index [IDX0_NUTR_FOOD_REQD]    Script Date: 22/10/2559 10:17:26 ******/
--CREATE UNIQUE CLUSTERED INDEX [IDX0_NUTR_FOOD_REQD] ON [dbo].[NUTR_FOOD_REQD]
--(
--	[REQID] ASC,
--	[REQCODE] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

/****** Object:  Index [PK_NUTR_FOOD_REQD]    Script Date: 22/10/2559 10:18:14 ******/
--ALTER TABLE [dbo].[NUTR_FOOD_REQD] ADD  CONSTRAINT [PK_NUTR_FOOD_REQD] PRIMARY KEY NONCLUSTERED 
--(
--	[REQID] ASC,
--	[REQCODE] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO


--NUTR_FOOD_REQS
/****** Object:  Index [IDX0_NUTR_FOOD_REQS]    Script Date: 22/10/2559 10:28:05 ******/
--CREATE UNIQUE CLUSTERED INDEX [IDX0_NUTR_FOOD_REQS] ON [dbo].[NUTR_FOOD_REQS]
--(
--	[REQID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--/****** Object:  Index [IDX1_NUTR_FOOD_REQS]    Script Date: 22/10/2559 10:28:23 ******/
--CREATE NONCLUSTERED INDEX [IDX1_NUTR_FOOD_REQS] ON [dbo].[NUTR_FOOD_REQS]
--(
--	[HN] ASC,
--	[AN] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--/****** Object:  Index [PK_NUTR_FOOD_REQS]    Script Date: 22/10/2559 10:28:40 ******/
--ALTER TABLE [dbo].[NUTR_FOOD_REQS] ADD  CONSTRAINT [PK_NUTR_FOOD_REQS] PRIMARY KEY NONCLUSTERED 
--(
--	[REQID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQS]  WITH CHECK ADD  CONSTRAINT [FK_NUTR_FOOD_REQS_NUTR_DIAG] FOREIGN KEY([DIAG])
--REFERENCES [dbo].[NUTR_DIAG] ([CODE])
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQS] CHECK CONSTRAINT [FK_NUTR_FOOD_REQS_NUTR_DIAG]
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQS]  WITH CHECK ADD  CONSTRAINT [FK_NUTR_FOOD_REQS_NUTR_PADM] FOREIGN KEY([AN])
--REFERENCES [dbo].[NUTR_PADM] ([AN])
--GO

--ALTER TABLE [dbo].[NUTR_FOOD_REQS] CHECK CONSTRAINT [FK_NUTR_FOOD_REQS_NUTR_PADM]
--GO


--NUTR_LOG
/****** Object:  Index [PK_NUTR_LOG]    Script Date: 22/10/2559 10:43:37 ******/
--ALTER TABLE [dbo].[NUTR_LOG] ADD  CONSTRAINT [PK_NUTR_LOG] PRIMARY KEY CLUSTERED 
--(
--	[ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO



--NUTR_MISC
/****** Object:  Index [PK_NUTR_MISC]    Script Date: 22/10/2559 10:49:44 ******/
--ALTER TABLE [dbo].[NUTR_MISC] ADD  CONSTRAINT [PK_NUTR_MISC] PRIMARY KEY CLUSTERED 
--(
--	[COD] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO


--NUTR_PADM
--/****** Object:  Index [IDX0_NUTR_PADM]    Script Date: 22/10/2559 10:52:23 ******/
--CREATE UNIQUE NONCLUSTERED INDEX [IDX0_NUTR_PADM] ON [dbo].[NUTR_PADM]
--(
--	[HN] ASC,
--	[AN] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--/****** Object:  Index [PK_NUTR_PADM]    Script Date: 22/10/2559 10:52:38 ******/
--ALTER TABLE [dbo].[NUTR_PADM] ADD  CONSTRAINT [PK_NUTR_PADM] PRIMARY KEY CLUSTERED 
--(
--	[AN] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

