CREATE FUNCTION FN_REPORT4(@FRDATE DATETIME, @TODATE DATETIME)
RETURNS TABLE
AS
RETURN
(
SELECT C.WARDID, C.WARDNAME, C.REQCODE, C.FDES, 6*SUM(DAYSCOUNT)+SUM(MEALS) AS MEALS
FROM
(
SELECT *, DATEDIFF(DAY,REQFR,REQTO) AS DAYSCOUNT
FROM
(
SELECT WARDID, WARDNAME, REQCODE, FDES, REQDATE, REQENDDATE, REQEND, 
       CASE WHEN CONVERT(DATE,@FRDATE) > CONVERT(DATE,REQDATE) THEN CONVERT(DATE,REQDATE) ELSE CONVERT(DATE,@FRDATE) END AS REQFR,
	   CASE WHEN CONVERT(DATE,@TODATE) > CONVERT(DATE,ISNULL(REQENDDATE,@TODATE)) THEN CONVERT(DATE,REQENDDATE) ELSE CONVERT(DATE,@TODATE) END AS REQTO,
	   A.MEALS
FROM
(
SELECT R.AN, R.REQDATE, R.REQEND, R.REQENDDATE, R.REQID, 
       P.WARDID, P.WARDNAME, 
       D.REQCODE, F.FDES, 
	   6-ISNULL(R.MEALORD,1)+1 AS MEALS,
       MIN(R.REQDATE) AS REQFR, MAX(REQENDDATE) AS REQTO
FROM NUTR_FOOD_REQS R
JOIN NUTR_FOOD_REQD D ON D.REQID = R.REQID
JOIN NUTR_FACT F ON F.CODE = D.REQCODE
JOIN NUTR_PADM P ON P.AN = R.AN
--WHERE R.AN = '5200018'--'5300010'
--AND F.FGRC = '0001'
--AND ISNULL(R.REQEND,'') = 'Y'
WHERE F.FGRC = '0001'
GROUP BY R.AN, R.REQDATE, R.REQEND, R.REQENDDATE, R.REQID, P.WARDID, P.WARDNAME, D.REQCODE, F.FDES, R.MEALORD) A) B) C
GROUP BY C.WARDID, C.WARDNAME, C.REQCODE, C.FDES
)