--SELECT *
--FROM NUTR_FACT

--SELECT *
--FROM NUTR_FACT_GRPS

--SELECT CODE, FDES 
--FROM NUTR_FACT
--WHERE FGRC = '0002'

--SELECT *
--FROM NUTR_FACT_GRPS G
--LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC
--WHERE G.FGRC = '0001'

--SELECT *
--FROM NUTR_FACT_GRPS G
--LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC
--WHERE G.FGRC = '0002'

--SELECT FGRC AS CODE, NOTE AS FDES
--FROM NUTR_FACT_GRPS
--WHERE PCOD = '0002'

SELECT *
FROM NUTR_FACT_GRPS G
LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC

--SELECT G.FGRC AS CODE, G.FGRP AS FDES
--FROM NUTR_FACT_GRPS G
--LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC
--WHERE G.FGRC = '0001'
--UNION
--SELECT G.FGRC AS CODE , G.FGRP AS FDES
--FROM NUTR_FACT_GRPS G
--LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC
--WHERE G.PCOD = '0001'
--UNION 
--SELECT CODE, FDES 
--FROM NUTR_FACT
--WHERE FGRC = '0001'

SELECT G.FGRC AS CODE , G.NOTE AS FDES, G.FPRP
FROM NUTR_FACT_GRPS G
LEFT JOIN NUTR_FACT F ON F.FGRC = G.FGRC
WHERE G.PCOD = '0222'
UNION 
SELECT CODE, FDES, '' AS FPRP 
FROM NUTR_FACT
WHERE FGRC = '0222'