CREATE PROCEDURE dbo.PROC_CHKDISCH_TOENDREQ
AS
BEGIN
UPDATE NUTR_FOOD_REQS
SET REQEND     = 'Y', 
    REQENDDATE = GETDATE(),
	REQENDTYPE = ''
FROM NUTR_FOOD_REQS R
WHERE ISNULL(R.REQEND,'') = ''
AND ISNULL(R.REQENDTYPE,'')= ''
AND EXISTS (SELECT 1 
            FROM DEVHC.dbo.Ipd_h 
			where (ISNULL(discharge_date,'') <> '') 
			AND ladmit_n = R.AN)
END