CREATE VIEW [dbo].[VW_REP001_FEEDBYCC] AS
SELECT 
RD.REQID
,T.FDES AS FOODTYPE
,B.FDES AS CONC
,C.FDES AS CC
,D.FDES AS MEAL
FROM NUTR_FOOD_REQD RD
JOIN NUTR_FACT T ON T.CODE = RD.REQCODE
                AND T.FGRC IN ('2414','2421')

JOIN (SELECT RD.REQID,C.FDES 
      FROM NUTR_FOOD_REQD RD
      JOIN NUTR_FACT C ON C.CODE = RD.REQCODE
                       AND C.FGRC IN ('2411','2422')) B ON B.REQID = RD.REQID

JOIN (SELECT RD.REQID,CC.FDES 
      FROM NUTR_FOOD_REQD RD
      JOIN NUTR_FACT CC ON CC.CODE = RD.REQCODE
                       AND CC.FGRC IN ('2412','2423')) C ON C.REQID = RD.REQID

JOIN (SELECT RD.REQID,M.FDES 
      FROM NUTR_FOOD_REQD RD
      JOIN NUTR_FACT M ON M.CODE = RD.REQCODE
                AND M.FGRC IN ('2413','2424')) D ON D.REQID = RD.REQID